### ISSUE TITLE
Building locally result in formatting error

### ISSUE THREAD

**Issue by mborisyak** [ShipSoft/shipdist#94] opened 2024-11-19 10:12 UTC
Hello!

When trying to build the recent FairShip (b4024b7fffa36e3b329c127c1e8e2fda73e16cf8) locally:
```bash
$ aliBuild build FairShip --config-dir shipdist/ --defaults release --always-prefer-system
Traceback (most recent call last):
  File "/home/max/opt/pyenv/versions/py3/bin/aliBuild", line 130, in <module>
    doMain(args, parser)
  File "/home/max/opt/pyenv/versions/py3/bin/aliBuild", line 83, in doMain
    doBuild(args, parser)
  File "/home/max/opt/pyenv/versions/3.10.4/envs/py3/lib/python3.10/site-packages/alibuild_helpers/build.py", line 490, in doBuild
    getPackageList(packages                = packages,
  File "/home/max/opt/pyenv/versions/3.10.4/envs/py3/lib/python3.10/site-packages/alibuild_helpers/utilities.py", line 469, in getPackageList
    requested_version = resolve_version(spec, defaults, "unavailable", "unavailable")
  File "/home/max/opt/pyenv/versions/3.10.4/envs/py3/lib/python3.10/site-packages/alibuild_helpers/utilities.py", line 126, in resolve_version
    return spec["version"] % {
TypeError: unsupported operand type(s) for %: 'float' and 'dict'
```

My system configuration:
- Ubuntu 22.04.5 LTS
- Python 3.10.4
- alibuild 1.17.12

I would appreciate any help!
Thanks!

**Comment by olantwin** [comment] 2024-11-19 10:32
This is either an issue with shipdist, or alibuild.

@antonioiuliano2 can you reproduce this on ubuntu 22.04?

**Comment by olantwin** [comment] 2024-11-19 10:32
Can't reproduce with python 3.10.4 on my machine.

**Comment by olantwin** [comment] 2024-11-19 10:34
Generally on ubuntu 22.04 I would recommend using the `cvmfs` build prepared by @antonioiuliano2

**Comment by mborisyak** [comment] 2024-11-19 10:36
I will try that, thanks!

**Comment by antonioiuliano2** [comment] 2024-11-19 11:11
I cannot reproduce it myself, but I agree with Oliver that the cvmfs version should work.

**Comment by olantwin** [comment] 2024-11-19 12:42
@mborisyak What does `which aliBuild` return?

**Comment by egamberini** [comment] 2024-11-19 14:10
Hi @mborisyak I had the same failure while building locally on an Alma Linux 9 container. The problem for me was some missing dep, in particular `gcc-c++` `boost-devel` (note that they might have slightly different names on Ubuntu). In general I would be checking if you have these installed, together with other basic packages such as `python-devel`, `cmake`, etc.

**Comment by mborisyak** [comment] 2024-11-19 14:12
> @mborisyak What does `which aliBuild` return?
I am using pyenv:
```bash
$ which aliBuild 
/home/max/opt/pyenv/shims/aliBuild
$ pyenv which aliBuild
/home/max/opt/pyenv/versions/py3/bin/aliBuild
$ which python
/home/max/opt/pyenv/shims/python
$ pyenv which python
/home/max/opt/pyenv/versions/py3/bin/python
$ pyenv versions
  system
  3.10.4
  3.10.4/envs/jax-legacy
  3.10.4/envs/py3
  3.12.3
  jax-legacy --> /home/max/opt/pyenv/versions/3.10.4/envs/jax-legacy
* py3 --> /home/max/opt/pyenv/versions/3.10.4/envs/py3 (set by PYENV_VERSION environment variable)
```

**Comment by mborisyak** [comment] 2024-11-19 14:36
Thank you @egamberini !

I belive, I have found the problem.

I have changed the aliBuild file a little ([`alibuild_helpers/utilities.py:126`](https://github.com/alisw/alibuild/blob/master/alibuild_helpers/utilities.py#L126)) to print the spec:
```
<a lot of dependencies>
OrderedDict([('package', 'UUID'), ('version', 'v2.27.1'), ('tag', 'alice/v2.27.1'), ('source', 'https://github.com/alisw/uuid'), ('build_requires', ['GCC-Toolchain:(?!osx)', 'autotools:(slc6|slc7)']), ('prepend_path', OrderedDict([('PKG_CONFIG_PATH', '$UUID_ROOT/share/pkgconfig')]))])
OrderedDict([('package', 'termcap'), ('version', 1.0), ('system_requirement_missing', 'Please install the ncurses development package on your system (usually ncurses-devel or libncurses-dev)'), ('system_requirement', '.*'), ('system_requirement_check', 'printf "#include <termcap.h>\\n" | gcc -xc++ - -c -o /dev/null\n')])
```
It seems like the `termcap` package somehow has a float as its version (I would bet YAML is somehow involved).

I made a small change:
```python
version = str(spec['version'])
return version % {
  ...
}
```
instead of
```python
return spec["version"] % {
...
}
```
and it works!

@egamberini You were right, I was missing a Ubuntu equivalent of Xdevel.

**Comment by olantwin** [comment] 2024-11-19 14:54
> Thank you @egamberini !
> 
> I belive, I have found the problem.
> 
> I have changed the aliBuild file a little ([`alibuild_helpers/utilities.py:126`](https://github.com/alisw/alibuild/blob/master/alibuild_helpers/utilities.py#L126)) to print the spec:
> 
> ```
> <a lot of dependencies>
> OrderedDict([('package', 'UUID'), ('version', 'v2.27.1'), ('tag', 'alice/v2.27.1'), ('source', 'https://github.com/alisw/uuid'), ('build_requires', ['GCC-Toolchain:(?!osx)', 'autotools:(slc6|slc7)']), ('prepend_path', OrderedDict([('PKG_CONFIG_PATH', '$UUID_ROOT/share/pkgconfig')]))])
> OrderedDict([('package', 'termcap'), ('version', 1.0), ('system_requirement_missing', 'Please install the ncurses development package on your system (usually ncurses-devel or libncurses-dev)'), ('system_requirement', '.*'), ('system_requirement_check', 'printf "#include <termcap.h>\\n" | gcc -xc++ - -c -o /dev/null\n')])
> ```
> 
> It seems like the `termcap` package somehow has a float as its version (I would bet YAML is somehow involved).
> 
> I made a small change:
> 
> ```python
> version = str(spec['version'])
> return version % {
>   ...
> }
> ```
> 
> instead of
> 
> ```python
> return spec["version"] % {
> ...
> }
> ```
> 
> and it works!

Could you report this to aliBuild please? (or submit the fix to them as a PR?)

It seems that aliBuild can't handle it if pyyaml parses the version as a float instead of a string.

> @egamberini You were right, I was missing a Ubuntu equivalent of Xdevel.

Concerning the dependencies, please make sure you have all packages listed [here](https://alice-doc.github.io/alice-analysis-tutorial/building/prereq-ubuntu.html) installed.

Closing this as solved.

**Closed by olantwin** 2024-11-19 14:54 UTC
Labels: question
